import { useState } from "react";
import { AlertTriangle, Users, Video, XCircle, Info, GraduationCap } from "lucide-react";

type Lang = "en" | "ml" | "hi";

const stepsByLang: Record<Lang, { n: number; t: string; d: string }[]> = {
  en: [
    { n: 1, t: 'Select Category', d: 'First, choose a category (Example: Instagram Followers, Likes, Views, etc.).' },
    { n: 2, t: 'Choose Service', d: 'After selecting the category, choose the service you prefer from the available services.' },
    { n: 3, t: 'Enter Quantity', d: 'Enter the quantity you want (Example: 1000).' },
    { n: 4, t: 'Enter Profile / Post / Reel Link', d: 'Paste the correct link. Example: Profile link · Post link · Reel link ⚠️ The link must be correct, otherwise the order will not work.' },
    { n: 5, t: 'Click on "Continue to Payment"', d: 'Click the Continue to Payment button.' },
    { n: 6, t: 'Send Payment to the Given QR Code', d: 'Scan the QR code shown on the screen and send the payment.' },
    { n: 7, t: 'Submit UTR / Transaction ID', d: 'After completing the payment, copy the UTR number / Transaction ID and paste it on the site.' },
    { n: 8, t: 'Click on "Submit & Order"', d: 'If all the details are correct, click Submit & Order.' },
    { n: 9, t: 'Send Automatically Generated Message to Admin', d: 'Send the message automatically generated by the site to the admin (via WhatsApp).' },
    { n: 10, t: 'Done 🎉', d: 'Your order has been successfully placed. Now wait for the service to start.' },
  ],
  ml: [
    { n: 1, t: 'Select Category', d: 'First, category choose cheyyuka (Example: Instagram Followers, Likes, Views, etc.)' },
    { n: 2, t: 'Choose Service', d: 'Category select cheyth kazhinjal, available services il ninn ningalkk ishtapetta oru service choose cheyyuka.' },
    { n: 3, t: 'Enter Quantity', d: 'Ningalk vendunna quantity (example: 1000) enter cheyyuka.' },
    { n: 4, t: 'Enter Profile / Post / Reel Link', d: 'Correct link paste cheyyanam. Example: Profile link · Post link · Reel link ⚠️ Link correct aayirikanam, illenkil order work cheyyilla.' },
    { n: 5, t: 'Click on "Continue to Payment"', d: 'Continue to payment button click cheyyuka.' },
    { n: 6, t: 'Send Payment to Given QR Code', d: 'Screen il kaanikunna QR code scan cheyth payment ayakkuka.' },
    { n: 7, t: 'Submit UTR / Transaction ID', d: 'Payment kazhinjal, UTR number / Transaction ID copy cheyth site il paste cheyyuka.' },
    { n: 8, t: 'Click on "Submit & Order"', d: 'Ella details correct aanenkil Submit & Order click cheyyuka.' },
    { n: 9, t: 'Send Automatically Entered Message to Admin', d: 'Site automatic ayi generate cheyyunna message admin inu send cheyyuka (WhatsApp).' },
    { n: 10, t: 'Done 🎉', d: 'Order successfully place aayi. Now wait for service to start.' },
  ],
  hi: [
    { n: 1, t: 'कैटेगरी चुनें', d: 'सबसे पहले एक कैटेगरी चुनें (जैसे: Instagram Followers, Likes, Views आदि)।' },
    { n: 2, t: 'सर्विस चुनें', d: 'कैटेगरी चुनने के बाद उपलब्ध सर्विसेज़ में से अपनी पसंद की सर्विस चुनें।' },
    { n: 3, t: 'क्वांटिटी दर्ज करें', d: 'आपको जितनी क्वांटिटी चाहिए (उदाहरण: 1000) वह दर्ज करें।' },
    { n: 4, t: 'प्रोफाइल / पोस्ट / रील लिंक डालें', d: 'सही लिंक पेस्ट करें। उदाहरण: Profile link · Post link · Reel link ⚠️ लिंक सही होना चाहिए, नहीं तो ऑर्डर काम नहीं करेगा।' },
    { n: 5, t: '"Continue to Payment" पर क्लिक करें', d: 'Continue to Payment बटन पर क्लिक करें।' },
    { n: 6, t: 'दिए गए QR Code पर पेमेंट भेजें', d: 'स्क्रीन पर दिख रहे QR code को स्कैन करके पेमेंट भेजें।' },
    { n: 7, t: 'UTR / Transaction ID सबमिट करें', d: 'पेमेंट करने के बाद UTR नंबर / Transaction ID कॉपी करके वेबसाइट में पेस्ट करें।' },
    { n: 8, t: '"Submit & Order" पर क्लिक करें', d: 'अगर सभी डिटेल्स सही हैं तो Submit & Order पर क्लिक करें।' },
    { n: 9, t: 'ऑटोमैटिक जनरेटेड मैसेज एडमिन को भेजें', d: 'वेबसाइट द्वारा ऑटोमैटिक जनरेट किया गया मैसेज WhatsApp पर एडमिन को भेजें।' },
    { n: 10, t: 'हो गया 🎉', d: 'आपका ऑर्डर सफलतापूर्वक प्लेस हो गया है। अब सर्विस शुरू होने का इंतजार करें।' },
  ],
};

const reminderByLang: Record<Lang, string> = {
  en: "Important Reminders: Your account must be public (especially for Instagram). Double-check the link before placing the order.",
  ml: "Important Reminders: Account public aayirikanam (especially Instagram). Link correct aanennu double check cheyyuka.",
  hi: "महत्वपूर्ण याद दिलाने वाली बातें: आपका अकाउंट public होना चाहिए (खासकर Instagram)। ऑर्डर करने से पहले लिंक दोबारा चेक करें।",
};

const headingByLang: Record<Lang, string> = {
  en: "HOW TO USE THIS WEBSITE",
  ml: "HOW TO USE THIS WEBSITE",
  hi: "इस वेबसाइट का उपयोग कैसे करें",
};

const langButtons: { code: Lang; label: string }[] = [
  { code: "ml", label: "🇮🇳 മലയാളം" },
  { code: "en", label: "🇬🇧 English" },
  { code: "hi", label: "🇮🇳 हिन्दी" },
];

const Guidelines = () => {
  const [lang, setLang] = useState<Lang>("en");
  const steps = stepsByLang[lang];

  return (
    <section className="container pb-16 max-w-3xl mx-auto space-y-6">
      {/* Important Guidelines */}
      <div className="card-surface border border-border/60 rounded-sm p-6 sm:p-8 space-y-6">
        <div className="flex items-center gap-3">
          <AlertTriangle className="h-5 w-5 text-primary" />
          <h2 className="display text-2xl font-black tracking-wider text-primary">IMPORTANT GUIDELINES</h2>
        </div>

        {/* IG Followers */}
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-sm font-bold text-foreground">
            <Users className="h-4 w-4 text-primary" />
            Before ordering Instagram Followers
          </div>
          <div className="border-l-2 border-primary/60 bg-muted/30 px-4 py-3 rounded-sm text-sm">
            Make sure your Instagram account is <span className="font-bold text-foreground">public</span> and the <span className="font-bold text-foreground">"Flagged for Review"</span> option is turned off.
          </div>
          <div className="border border-border bg-muted/20 rounded-sm p-4 space-y-2">
            <div className="text-xs font-black uppercase tracking-widest text-primary">❗ HOW TO TURN OFF "FLAGGED FOR REVIEW"</div>
            <ol className="list-decimal list-inside text-sm space-y-1 text-muted-foreground">
              <li>Go to Instagram Settings</li>
              <li>Select Invite and Follow Friends</li>
              <li>Disable Flagged for Review</li>
            </ol>
          </div>
          <ul className="space-y-1.5 text-sm text-muted-foreground">
            <li className="flex items-center gap-2"><XCircle className="h-4 w-4 text-primary shrink-0" /> No refund after the order is placed</li>
            <li className="flex items-center gap-2"><XCircle className="h-4 w-4 text-primary shrink-0" /> No refill if the profile is made private or the username is changed</li>
          </ul>
        </div>

        <div className="border-t border-border/60" />

        {/* Reel/Post Views or Likes */}
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-sm font-bold text-foreground">
            <Video className="h-4 w-4 text-primary" />
            Before ordering Instagram Reel/Post views or likes
          </div>
          <div className="border-l-2 border-primary/60 bg-muted/30 px-4 py-3 rounded-sm text-sm">
            Make sure <span className="font-bold text-foreground">all accounts in the collab are public</span>. Your account must also be public.
          </div>
          <p className="text-sm text-muted-foreground">
            If any account is private, the order cannot be completed and <span className="font-bold text-foreground">no refund will be provided</span>.
          </p>
          <div className="border-l-2 border-primary/60 bg-muted/30 px-4 py-3 rounded-sm text-sm flex items-start gap-2">
            <Info className="h-4 w-4 text-primary shrink-0 mt-0.5" />
            <span>Please remove private collab accounts before ordering these services.</span>
          </div>
        </div>
      </div>

      {/* How to use */}
      <div className="card-surface border border-border/60 rounded-sm p-6 sm:p-8 space-y-5">
        <div className="flex items-center justify-between gap-3 flex-wrap">
          <div className="flex items-center gap-3">
            <GraduationCap className="h-5 w-5 text-primary" />
            <h2 className="display text-2xl font-black tracking-wider text-primary">{headingByLang[lang]}</h2>
          </div>
          <div className="flex items-center gap-1.5 flex-wrap">
            {langButtons.map((b) => (
              <button
                key={b.code}
                type="button"
                onClick={() => setLang(b.code)}
                className={`text-xs font-bold px-3 py-1.5 rounded-full border transition-colors ${
                  lang === b.code
                    ? "bg-primary text-primary-foreground border-primary"
                    : "bg-muted/30 text-muted-foreground border-border hover:border-primary/50 hover:text-foreground"
                }`}
              >
                {b.label}
              </button>
            ))}
          </div>
        </div>

        <ol className="space-y-3">
          {steps.map((s) => (
            <li key={s.n} className="flex gap-3 pb-3 border-b border-border/40 last:border-0">
              <div className="h-7 w-7 shrink-0 rounded-sm bg-primary/15 border border-primary/40 grid place-items-center text-xs font-black text-primary">
                {s.n}
              </div>
              <div className="flex-1">
                <div className="text-sm font-bold text-foreground mb-0.5">
                  {s.t} <span className="text-primary">👉</span>
                </div>
                <div className="text-sm text-muted-foreground">{s.d}</div>
              </div>
            </li>
          ))}
        </ol>

        <div className="border-l-2 border-primary bg-primary/10 px-4 py-3 rounded-sm flex items-start gap-2 text-sm">
          <AlertTriangle className="h-4 w-4 text-primary shrink-0 mt-0.5" />
          <span>
            <span className="font-bold text-foreground">⚠️</span> {reminderByLang[lang]}
          </span>
        </div>
      </div>
    </section>
  );
};

export default Guidelines;
